version: '3.3'
services:
  grafana:
    image: grafana/grafana:7.0.1
    ports:
      - 3000
    networks:
      - public
    secrets:
      - MONITOR_ADMIN_USER
      - MONITOR_ADMIN_PASSWORD
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/MONITOR_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/MONITOR_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=false
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
          - traefik.enable=true
          - traefik.docker.network=public
          - traefik.constraint-label=public
          - traefik.http.routers.grafana.rule=Host(`${MONITOR_DOMAIN?Variable not set}`)
          - traefik.http.routers.grafana.entrypoints=http
          - traefik.http.middlewares.grafana.redirectscheme.scheme=https
          - traefik.http.middlewares.grafana.redirectscheme.permanent=true
          - traefik.http.routers.grafana-secured.rule=Host(`${MONITOR_DOMAIN?Variable not set}`)
          - traefik.http.routers.grafana-secured.entrypoints=https
          - traefik.http.routers.grafana-secured.tls.certresolver=le
          - traefik.http.services.grafana-secured.loadbalancer.server.port=3000
    volumes:
      - grafana:/var/lib/grafana
  influxdb:
    image: influxdb:1.8.0
    ports:
      - 8086
    networks:
      - public
      - shiny-net
    deploy:
      resources:
        reservations:
          cpus: '0.3'
          memory: 128M
        limits:
          cpus: '0.6'
          memory: 512M
      placement:
        constraints:
          - node.role==manager
    environment:
      INFLUXDB_DB: shinyproxy_usagestats # this need to match the database specified in application.yml
      # INFLUXDB_ADMIN_USER: admin
      # INFLUXDB_ADMIN_PASSWORD: admin
      # INFLUXDB_HTTP_AUTH_ENABLED: "true" # need to delete volume if change the database environment
    volumes:
        - influxdb:/var/lib/influxdb
networks:
  public:
    external: true
  shiny-net:
    external: true
secrets:
  MONITOR_ADMIN_USER:
    external: true
  MONITOR_ADMIN_PASSWORD:
    external: true
volumes:
  grafana:
  influxdb: